// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAxQmMmjCRcNqaxFtz3MqFLq5Gkoojhs',
    appId: '1:895856838810:web:d1e7fed6f2795d11443723',
    messagingSenderId: '895856838810',
    projectId: 'smart-quiz-351ef',
    authDomain: 'smart-quiz-351ef.firebaseapp.com',
    storageBucket: 'smart-quiz-351ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZtaIMq_aWIGn8Xpycs4zQU5Sw5hYP38g',
    appId: '1:895856838810:android:9372c78fa2843248443723',
    messagingSenderId: '895856838810',
    projectId: 'smart-quiz-351ef',
    storageBucket: 'smart-quiz-351ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdih3VZ7ENol4EVLTNLBlh6qb_4_EvaMk',
    appId: '1:895856838810:ios:0c2b5a13ef6cbb58443723',
    messagingSenderId: '895856838810',
    projectId: 'smart-quiz-351ef',
    storageBucket: 'smart-quiz-351ef.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdih3VZ7ENol4EVLTNLBlh6qb_4_EvaMk',
    appId: '1:895856838810:ios:0c2b5a13ef6cbb58443723',
    messagingSenderId: '895856838810',
    projectId: 'smart-quiz-351ef',
    storageBucket: 'smart-quiz-351ef.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZAxQmMmjCRcNqaxFtz3MqFLq5Gkoojhs',
    appId: '1:895856838810:web:4f03cb5cb08bc287443723',
    messagingSenderId: '895856838810',
    projectId: 'smart-quiz-351ef',
    authDomain: 'smart-quiz-351ef.firebaseapp.com',
    storageBucket: 'smart-quiz-351ef.firebasestorage.app',
  );
}
